### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by bishalkc** [datosgobar/portal-andino-theme#11]
Couple of good to have options. 
- [ ] CSS styling (add few more color schemes to the theme)
- [ ] Multiple language options (defaults to one language and option to configure other, may be link next to About to select **English** )
- [ ] PDF View and resource_proxy
- [ ] CKAN 2.7 support

**Comment by iheredia** [comment]
¡Hi, @bishalkc!

Thanks for opening this issue. We really appreciate the feedback.

Regarding the color schemes: we are currently working with 4 main colors, specified on [this file](https://github.com/datosgobar/portal-andino-theme/blob/master/ckanext/gobar_theme/styles/sass/utils/colors.scss). These colors are picked from the argentine national identity and are used by the national officess that use this app.

In a next iteration we'll add the posibility to pick a few colors to be used instead of the default ones, and maybe also a secondary color scheme to be used instead. But it's not our priority to give more complex css decisions to the site administrator right now. 

Regarding alternative languages: since this is an official national project, the default language is the same as the national language: Spanish. We'd love to translate the project to english and other languages, but currently with are overloaded with other tasks. Maybe we can add little incremental changes (for example: start by translating the readmes) but it'll be a slow process. If you know some Spanish I'd encourage you to start translating the project into english. We'll be happy to review a pull request on this topic :D 

Have a nice week,
The Argentine Data Team

**Comment by bishalkc** [comment]
Thank you for your quick response and consideration of feature request. I have already translated the theme to English and a prototype can be seen here (still no data yet) http://dataportal.datanepal.com, I am making few last minute changes and I will push the translated theme [here](https://github.com/bishalkc/portal-andino-theme). 

Also I added one more feature request above (PDF View and resource_proxy), I added these two to production.ini plugins section but the app wont start, I still need to dig in deep but initial error is "Can't initialize database". 

Again, thank you for listening and for your help. 

Happy Holidays!!!
